const recipes = [
  {
    name: "Creamy Butter Mashed Potatoes",
    servings: "4 SERVINGS",
    ingredients: [
      "2 1/2 pounds Yukon Gold Potatoes (or Organic Yellow Potatoes for substitute)",
      "1 1/2 cups unsalted butter",
      "3/4 cup whole milk",
      "1/2 cup heavy cream",
      "Kosher salt",
    ],
    directions: [
      "Wash Potatoes and Place in salted water that covers them",
      "Bring to boil, then reduce to steady simmer for 35-45 minutes (knife slides in w no resistance)",
      "Drain and let rest for 5 minutes",
      "Warm up the milk and cream together in small pot",
      "Take off skins",
      "Use potato ricer (or box grater or sieve for substitute) for mashing and put into pot off heat until ready",
      "When ready put pot on low heat and add cubes of butter gradually and then slowly incorporate milk/cream",
      "Be stirring gently not mashing or smushing — add remaining salt, pepper, etc. to taste and done",
    ],
  },
  {
    name: "Red Wine Reduction Sauce (Bordelaise)",
    servings: "",
    notes: "MORE NEXT TIME (LITTLE BIT FOR 4 PEOPLE)",
    ingredients: [
      "2 tbsp unsalted butter",
      "2 large shallots",
      "1 Garlic clove",
      "1 1/2 cups of Cabernet Sauvignon (or Bordeaux/Merlot)",
      "3/4 cup low-sodium beef stock",
      "1 Sprig of Thyme",
      "Kosher salt and black pepper and maybe balsamic vinegar or honey",
    ],
    directions: [
      "Medium-low saucepan add 1 tbsp butter, diced shallots, and pinch of salt and sweat for 7/8 mins",
      "Add garlic in for 45 seconds to not burn",
      "Add 1 1/2 cups of red wine and bring to a gentle simmer, then lower to medium-low for 30-35 mins (reduce by 2/3 and make it syrupy - stirring every few mins)",
      "Add 3/4 cups of beef stock and sprig of thyme and keep on bare simmer for 20 mins until sauce coats back of spoon",
      "Remove from heat and whisk in 1 tbsp of cold butter — add remaining salt, pepper, etc. to taste and add in a little honey if sharp, or balsamic if flat and done",
    ],
  },
  {
    name: "Bolognese Sauce Pasta",
    servings: "4 SERVINGS",
    ingredients: [
      "Mirpouix (I typically go 1.5x onion to /1/1 carrot/celery)",
      "1lb pasta",
      "1lb ground beef (85/15 or 80/20)",
      "Optional: pack of panchetta, guanciale, or some small portion of ground pork (more meat more flavour)",
      "1.5-2x 32oz carton chicken stock",
      "Dry white wine (I normally use a Pinot Grigio) ~1/3-1/2 bottle",
      "1x 16oz can hunts tomato sauce (plain), or 1x 32 oz sanmarzanos and break em up",
      "Good parm (fresh grated from block or it won’t melt)",
      "2x-4x cloves of garlic (around 2tbsp after mincing)",
      "Crushed red pepper",
      "Bay leaves",
      "Optional: 1-2 tbsp of tomato paste, typically done when doing hunts sauce",
    ],
    directions: [
      "Sauté ground beef in 1-2 tbsp olive oil, then season with a lil salt and pepper towards end (Let sit a bit at first to get brown crusty bottom on pieces)",
      "Remove beef but leave fat in pan",
      "If doing panchetta/guanciale, sauté in the pan until golden/crispy",
      "Remove panchetta/guanciale but leave fat in pan",
      "Mirepoix in pan with the fat in it (sauté until onions are translucent and carrot/celery softens)",
      "Garlic in for about 45 seconds (don’t burn)",
      "If adding tomato paste, add it and cook down 1.5-3 minutes",
      "Toast 1-2 tbsp red pepper flakes in olive oil on the side of the pan for 45 seconds and then incorporate into veg",
      "Win in, deglaze fond on bottom of pan by scraping. Cook down until at least 1/2 reduced and alcohol all gone",
      "Tomato (sauce) in (if adding whole sanmarzanos, you just gotta crush them up as it cooks down. Every stir when liquid is low try and break them)",
      "Add 1 carton of chicken stock and a bay leaf, and bring to a simmer",
      "Reduce at medium/medium-low simmer over 1.5-3 hours, adding no more than both 32oz cartons of chicken stock, typically use 1.5",
      "When the sauce gets dry and liquid gets low, add more stock, stir in, let reduce",
      "When happy with texture and stock is used (minimal liquid at bottom and liquid is thickened when you pull it apart making an opening), turn heat to low/off",
      "Grate cheese in to your liking, 1-2 tbsp of butter, optional 1-2 tbsp of dried basil/oregano and stir for 1-2 minutes so cheese incorporates and doesn’t stick to pan",
      "Mix in pasta and add pasta water as necessary to loosen it up. Normally go thicker on the sauce with minimal liquid, and add pasta water to loosen it and let the sauce coat every piece of pasta well",
    ],
    notes:
      "Cut carrot and celery very small so they cook quicker and are less present in sauce at the end. Make a little hole at the side of the pan and toast red pepper flakes in 1-2 tbsp of olive oil there. Pre shredded cheese often has additives/anti coagulants, so try and buy a block and grate it otherwise the cheese can clump up and stick to the bottom of the pan when u add it in. Once simmering check it every 15-20mins or so, when it gets low add more stock",
  },
  {
    name: "Garlic Bread",
    servings: "4 SERVINGS",
    ingredients: [
      "Baguette",
      "4 tbsp unsalted butter",
      "2-4 cloves garlic, finely minced",
      "1-2 tbsp grated Parmesan",
      "Shredded mozzarella",
    ],
    directions: [
      "Heat oven to 425 degrees Fahrenheit",
      "Slice bread lengthwise",
      "Mix butter + garlic + parm + a little salt and spread over bread",
      "Bake 6 minutes and then add mozzarella over top",
      "Bake 3-5 more minutes until melted (broil briefly at the end if you want browning)",
    ],
  },
  {
    name: "Chicken Pot Pie",
    servings: "",
    ingredients: [
      "1 pack boneless, skinless chicken breast “strips”",
      "1 can cream of celery soup",
      "1 to 1 1/4 cup chicken broth",
      "3/4 to 5/6 stick of butter",
      "1 cup self-rising flour",
      "1 cup milk",
    ],
    directions: [
      "Bake chicken in oven for about 20 minutes at 350",
      "Cut into little pieces and cover the bottom of a pan/dish with chicken",
      "Mix together celery soup and chicken broth and pour it over the chicken",
      "Dot with 1/4 to 1/3 stick of butter and sprinkle salt and paper on it",
      "Mix flour and milk together and pour over chicken mixture",
      "Melt 1/2 stick of butter and pour over flour and milk",
      "Bake at 425 for 25 minutes or until light brown",
    ],
  },
];
